name: Repo Integrity

on: workflow_call

jobs:
  deps-integrity:
    name: Dependency Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ğŸ Verify conditions
        id: verify-conditions
        uses: ./.github/actions/verify-conditions

      - name: ğŸ“¦ Install dependencies
        if: steps.verify-conditions.outputs.check-deps-integrity == 'true'
        uses: ./.github/actions/install-deps

      - name: ğŸš¨ Check for vulnerabilities in dependencies
        if: steps.verify-conditions.outputs.check-deps-integrity == 'true'
        continue-on-error: true
        run: pnpm audit

      - name: ğŸ“œ Check for outdated dependencies
        if: steps.verify-conditions.outputs.check-deps-integrity == 'true'
        continue-on-error: true
        run: pnpm outdated

  other-repo-checks:
    name: Other Repo Checks
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¤” What should we check next?
        run: echo 'What should we check next? ğŸ¤·â€â™‚ï¸'
